### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

### ISSUE THREAD

**Issue by farzadmohseni-ir** [ElmiiiRaa/align_iranian_national_id_card#2]
**_When running with Python 3.8.3 , even though all the libraries are installed, I get the following error :_**

AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

![image](https://user-images.githubusercontent.com/57835828/110289724-14f63580-7fff-11eb-809d-cbbb7ce88853.png)

Please help fix the bug and run the project .

**Comment by farzadmohseni-ir** [comment]
**The following error can be fixed according to the evidence in stackoverflow .**

https://stackoverflow.com/questions/57218559/unable-to-enable-tensorflows-eager-execution

> ![1](https://user-images.githubusercontent.com/57835828/110444776-a682a780-80d2-11eb-8570-ba5e84ec44b7.jpg)

> ![2](https://user-images.githubusercontent.com/57835828/110444796-ab475b80-80d2-11eb-85b4-4e872e2661dd.jpg)

> ![3](https://user-images.githubusercontent.com/57835828/110444816-b0a4a600-80d2-11eb-88cf-92f3b61f1f99.jpg)

**Now, by executing the code, we will get a directory error that you did not publish such a file in the post. **_" fra.txt "_**
if possible Update project files .**

**Comment by ElmiraGhorbani** [comment]
> AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

check: [https://stackoverflow.com/questions/56127592/attributeerror-module-tensorflow-has-no-attribute-configproto](url)
